### ISSUE TITLE
Warning for next release

### ISSUE THREAD

**Issue by ThatOneCalculator** [YunoHost-Apps/calckey_ynh#10]
We're switching from `yarn` to `pnpm`. 

The process for installing packages is now:

```
corepack enable
corepack prepare pnpm@latest --activate
pnpm i
```

Futhermore, all `yarn run` should be replaced with `pnpm run` and all `yarn workspace` with `pnpm --filter`

**Comment by lapineige** [comment]
Thank you for the guidance 😃

**Comment by oufmilo** [comment]
#12 resolved in this PR
