### ISSUE TITLE
Not in Catalog

### ISSUE THREAD

**Issue by ThatOneCalculator** [YunoHost-Apps/calckey_ynh#24]
![image](https://user-images.githubusercontent.com/44733677/225206958-04406db4-af82-4168-baf3-a71f6d857ef5.png)

**Comment by lapineige** [comment]
But it's in the catalog https://github.com/YunoHost/apps/blob/master/apps.toml#L299 🤔

**Comment by ThatOneCalculator** [comment]
Strange...

**Comment by ThatOneCalculator** [comment]
Nvm, seems to be a problem with a lot of ynh apps.

**Comment by lapineige** [comment]
Maybe the app catalog service is buggy/available for some reason 🤔

**Comment by ThatOneCalculator** [comment]
This is still happening...

**Comment by lapineige** [comment]
ping @YunoHost-Apps/apps-group, is anyone has an idea… Calckey_ynh is in the app catalog, flagged as working, but here it is flagged as broken, and the *Install with Yunohost* button fails*

**Comment by tituspijean** [comment]
The bug seems to be coming from YunoHost's infrastructure. `calckey` is not present in catalog v2 (https://app.yunohost.org/default/v2/apps.json), but it is in v3 (https://app.yunohost.org/default/v3/apps.json).

**Comment by tituspijean** [comment]
Solved by changing the catalog version in our internal app. :)

**Comment by lapineige** [comment]
Oh it's funny that we are migration to app packaging v2 but app catalog v3 :D
Thanks !

**Comment by PhieF** [comment]
I still don't have it on raspberry pi

**Comment by alexAubin** [comment]
What version of YunoHost are you running
