### ISSUE TITLE
Not in the YunoHost app catalog

### ISSUE THREAD

**Issue by ThatOneCalculator** [YunoHost-Apps/calckey_ynh#3]
Hello!

I'm the lead developer of Calckey, and I'm very happy to see that a Yunohost package has been made for Calckey. I don't use Yunohost personally, but a lot of people have been asking for it :)

I tried going to the link in the readme (<https://install-app.yunohost.org/?app=calckey>), but it says that "This application is not in YunoHost's app catalog." When can users expect to see this in the catalog?

**Comment by lapineige** [comment]
That should be done soon, I make the pull request to add it in the catalog.
Very happy to see there is already a package for it, well done @oufmilo ! :smiley:

**Comment by lapineige** [comment]
Done 🙂
