### ISSUE TITLE
Error restoring from backup when files have been added to /var/www/calckey/packages/backend/assets/

### ISSUE THREAD

**Issue by trendless** [YunoHost-Apps/calckey_ynh#34]
### Describe the bug

- restoring Calckey backup on freshly setup Yunohost server fails when backup has files in /var/www/calckey/packages/backend/assets/

### Context

- OVH baremetal dedicated; 32GiB ram, 1TiB ssd
- Debian 11
- YunoHost version: 11.1.18
- I have full root access to the server
- nothing has been manually tweaked
- attempting to restore Calckey Version 13.1.4.1~ynh1

### Steps to reproduce

- upload $backup.tar via SCP
- in webadmin, navigate to Backup > Local archives /home/yunohost.backup > 10 days ago $backup (3 GB) /home/yunohost.backup/archives/$backup.tar
- deselect all but 'Calckey $Name calckey (3 GB) Version 13.1.4.1~ynh1'
- click 'Restore'
- installation of app/dependencies et al completes successfully, restoration of first encountered file in /var/www/calckey/packages/backend/assets/ fails with permissions issue, restore is rolled back
- *{same happens if attempted again after reboot}*

### Expected behavior

- app to be restored to working state

### Logs

https://paste.yunohost.org/raw/udepibivab

```
2023-05-07 16:47:51,803: DEBUG - [16:47:51] 'copy:backend:custom' errored after 324 ms
2023-05-07 16:47:51,804: DEBUG - [16:47:51] Error: EACCES: permission denied, open '/var/www/calckey/packages/backend/assets/clouds-high.jpg'
2023-05-07 16:47:51,804: DEBUG - [16:47:51] 'build' errored after 327 ms
2023-05-07 16:47:51,812: DEBUG -  ELIFECYCLE  Command failed with exit code 1.
2023-05-07 16:47:51,825: DEBUG -  ELIFECYCLE  Command failed with exit code 1.
2023-05-07 16:47:51,838: DEBUG - + ynh_exit_properly
2023-05-07 16:47:51,839: DEBUG - + [[ restore =~ ^install$|^upgrade$|^restore$ ]]
2023-05-07 16:47:53,344: ERROR - Could not restore calckey: An error occured inside the app restore script
```

**Comment by lapineige** [comment]
Do you know the permissions associated with this folder / those files ?

You added it manually from command line ?

**Comment by trendless** [comment]
The OS/Yuno install they were backed up from no longer exists; if I extract the tar, the file it stumbles over is 0644 as are all the rest of the assets I added. Other files in the same directory that I *didn't* add (ie they are included in the default install) are 0640, some of which come alphabetically before the one it stumbles over, so I infer that there are no permissions issues with them.

The ones I added, I did so via elevated CLI to ./custom/assets/ [as suggested here under 'Customize'](https://codeberg.org/calckey/calckey) then ran gulp to rebuild.. which I assume pulled them into /var/www/calckey/packages/backend/assets/ ?

---

Further troubleshooting: 
- extracted the tar
- removed all files I added from /var/www/calckey/packages/backend/assets/, left all default files
- created new tar; owned by root, 0666 like backups created by ynh
- reboot server so ynh creates associated json file and altered backup is visible in webadmin ui
- select altered backup in webadmin ui ; all backup items visible
- unselect all but calckey app
- 'restore'
- fails again; same kind of error, completely different location, still node-related, may or may not be related to the addition of the files?
- https://paste.yunohost.org/raw/usepenetef
```
2023-05-07 18:37:01,663: DEBUG - + sudo -u calckey env PATH=/opt/node_n/n/versions/node/19/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin pnpm install
2023-05-07 18:37:02,106: DEBUG - Internal Error: EACCES: permission denied, mkdir '/var/www/calckey/.cache/node/corepack'
2023-05-07 18:37:02,106: DEBUG - Error: EACCES: permission denied, mkdir '/var/www/calckey/.cache/node/corepack'
2023-05-07 18:37:02,115: DEBUG - + ynh_exit_properly
2023-05-07 18:37:02,116: DEBUG - + [[ restore =~ ^install$|^upgrade$|^restore$ ]]
2023-05-07 18:37:03,622: ERROR - Could not restore calckey: An error occured inside the app restore script
```

**Comment by lapineige** [comment]
> The OS/Yuno install they were backed up from no longer exists

Uh, that might be an issue for troubleshooting :/


> extracted the tar
removed all files I added from /var/www/calckey/packages/backend/assets/, left all default files
created new tar; owned by root, 0666 like backups created by ynh

Could you instead remove the file from the tar without extracting and recreating it ? This way no right would be affected.
(make a backup first)


> reboot server so ynh creates associated json file and altered backup is visible in webadmin ui


Wait, it does that ? 😮

**Comment by oufmilo** [comment]
> ### Describe the bug
> 
>     * restoring Calckey backup on freshly setup Yunohost server fails when backup has files in /var/www/calckey/packages/backend/assets/
> 
> 
> ### Context
> 
>     * OVH baremetal dedicated; 32GiB ram, 1TiB ssd
> 
>     * Debian 11
> 
>     * YunoHost version: 11.1.18
> 
>     * I have full root access to the server
> 
>     * nothing has been manually tweaked
> 
>     * attempting to restore Calckey Version 13.1.4.1~ynh1
> 
> 
> ### Steps to reproduce
> 
>     * upload $backup.tar via SCP
> 
>     * in webadmin, navigate to Backup > Local archives /home/yunohost.backup > 10 days ago $backup (3 GB) /home/yunohost.backup/archives/$backup.tar
> 
>     * deselect all but 'Calckey $Name calckey (3 GB) Version 13.1.4.1~ynh1'
> 
>     * click 'Restore'
> 
>     * installation of app/dependencies et al completes successfully, restoration of first encountered file in /var/www/calckey/packages/backend/assets/ fails with permissions issue, restore is rolled back
> 
>     * _{same happens if attempted again after reboot}_
> 
> 
> ### Expected behavior
> 
>     * app to be restored to working state
> 
> 
> ### Logs
> 
> https://paste.yunohost.org/raw/udepibivab
> 
> ```
> 2023-05-07 16:47:51,803: DEBUG - [16:47:51] 'copy:backend:custom' errored after 324 ms
> 2023-05-07 16:47:51,804: DEBUG - [16:47:51] Error: EACCES: permission denied, open '/var/www/calckey/packages/backend/assets/clouds-high.jpg'
> 2023-05-07 16:47:51,804: DEBUG - [16:47:51] 'build' errored after 327 ms
> 2023-05-07 16:47:51,812: DEBUG -  ELIFECYCLE  Command failed with exit code 1.
> 2023-05-07 16:47:51,825: DEBUG -  ELIFECYCLE  Command failed with exit code 1.
> 2023-05-07 16:47:51,838: DEBUG - + ynh_exit_properly
> 2023-05-07 16:47:51,839: DEBUG - + [[ restore =~ ^install$|^upgrade$|^restore$ ]]
> 2023-05-07 16:47:53,344: ERROR - Could not restore calckey: An error occured inside the app restore script
> ```

Can you try to restore again ?

**Comment by trendless** [comment]
Sure!

Looks like the same error as the second time: https://paste.yunohost.org/raw/ulupijuxec

**Comment by oufmilo** [comment]
Ok you should edit the restore script in your backup. You need to download your archive backup via FTP edit the restore script and upload again ! 

Just copy this in your restore script :
https://github.com/YunoHost-Apps/calckey_ynh/blob/1bebc6c2891ba4f5a2481ac4c1117492df0f8147/scripts/restore

Can you try this and give me the result ?

**Comment by lapineige** [comment]
> You need to download your archive backup via FTP edit the restore script and upload again !

Don't do that : it will mess up with the file rights (owner will be your PC user, not the original one from your server (root)) and that might be an issue.

Instead in your server `/home/yunohost.backup/archives` directory, as root, run `tar -xf calckey-upgrade-file-CHANGETHATNAME.tar  "apps/calckey/settings/scripts/restore"`.
This will extract the file to the subfolder : `apps/calckey/settings/scripts/restore`.
Then edit it (still as root).
Then from the same `archives` folder run `tar -uf calckey-upgrade-file-CHANGETHATNAME.tar  "apps/calckey/settings/scripts/restore"` (this will update the file in the archive)

**Comment by trendless** [comment]
Alas, the backup is compressed. I know we discussed before that extracting and recompressing could introduce problems. Any suggestions?

**Comment by oufmilo** [comment]
If you follow the lapineige « tuto » it’s Ok 👍

**Comment by trendless** [comment]
Those commands don't work on compressed archives, as far as I know.

**Comment by oufmilo** [comment]
You must be login as root

`cd /home/yunohost.backup/archives/`
`tar -xf ARCHIVENAME.tar "apps/calckey/settings/scripts/restore"`
`nano apps/calckey/settings/scripts/restore`¹
`tar -uf ARCHIVENAME.tar  "apps/calckey/settings/scripts/restore"`

¹Edit the file with 
https://github.com/YunoHost-Apps/calckey_ynh/blob/1bebc6c2891ba4f5a2481ac4c1117492df0f8147/scripts/restore


And after that you can restore your backup normally !

**Comment by lapineige** [comment]
> Those commands don't work on compressed archives, as far as I know.

Because you need to add the option to handle compressed archives `z` (`tar -xzf` and `tar -uzf`).

>  I know we discussed before that extracting and recompressing could introduce problems. 

If done as root (archive owner stays the same), I don't think so.
If done on your personal computer, certainly yes.

**Comment by trendless** [comment]
`root@myserver:/home/yunohost.backup/archives# tar -uzf 20230622-004813.tar  "apps/calckey/settings/scripts/restore"`
`tar: Cannot update compressed archives`
`Try 'tar --help' or 'tar --usage' for more information.`

Same if I target the tar.gz directly.

I had to `gunzip`, `tar -xf`, copy/paste, `tar -uf`, `gzip`, to successfully update the archive. And then the restore worked. 

Thanks so much for doing this, folks!! 🙌

**Comment by lapineige** [comment]
> root@myserver:/home/yunohost.backup/archives# tar -uzf 20230622-004813.tar  "apps/calckey/settings/scripts/restore"

That's not a compressed archive, just a .tar, not a .tar.gz :thinking:

**Comment by trendless** [comment]
It seems like when this is enabled:
![image](https://github.com/YunoHost-Apps/calckey_ynh/assets/1134495/222b72b3-8554-45b3-8102-e76a2649fdbd)

This is what's created:
![image](https://github.com/YunoHost-Apps/calckey_ynh/assets/1134495/74fbdb94-5afa-4817-92bd-779569460f0f)

As I specified above, I did try the tar commands inclusive of the -z option, on both the .tar and .tar.gz files, to no avail. Googling seems to confirm that -u does not work on compressed archives, but 🤷

**Comment by lapineige** [comment]
> seems to confirm that -u does not work on compressed archives, but shrug

Oh yes, that's true, I forgot that.
Yet you can decompress it and use that command.
