### ISSUE TITLE
Testing branch update.

### ISSUE THREAD

**Issue by Ciechom** [YunoHost-Apps/calckey_ynh#38]
Hey, can we get release candidate 2 on testing branch?

**Comment by lapineige** [comment]
I think @oufmilo is working on the previous release candidate, for my part considering the difficulties to update I won't invest any effort until the final release :sweat_smile:

**Comment by Ciechom** [comment]
The 1st release candidate is on testing branch and I updated to it without any problems, I guess it shouldn't be too difficult to update the package to 2nd release candidate.

**Comment by lapineige** [comment]
Oh, good catch, I didn't know it. Congrats @oufmilo !

I submitted a PR (you could have done it 😉, all it's needed is to change the source URL and provide the associated sha256sum), not tested yet.

**Comment by lapineige** [comment]
And… it fails.
This is going to be a bit more complex ^^

**Comment by lapineige** [comment]
See #39, we will wait for the final version.

**Comment by ThatOneCalculator** [comment]
That's a good idea. It may be a good idea to do a test with rc3 when it comes out though, as all issues will be fixed and it'll have a slightly new build procedure. Since the difference between stable and rc is already pretty large with the introduction with Rust and all that, it'd be a good idea to make sure everything works prior to the release of the stable version. Furthermore, we will be changing our name for the stable version, so that's something to take into account.

**Comment by lapineige** [comment]
>  It may be a good idea to do a test with rc3 when it comes out though, as all issues will be fixed and it'll have a slightly new build procedure
> Since the difference between stable and rc is already pretty large with the introduction with Rust and all that, it'd be a good idea to make sure everything works prior to the release of the stable version. 

Taking notes, thanks :)

> Furthermore, we will be changing our name for the stable version, so that's something to take into account.

Yes (related discussion #36), not sure how we will handle this for now… (I'd bet it would still be "calckey" in Yunohost for a while)


(I forgot to close this… oh wait, I can't. @Ciechom can you close the issue please ?)

**Comment by Ciechom** [comment]
Closing.

But a big warning: Testing branch 14rc has a bug that stops calckey from working and fills the log with "bad system call"

link to log: https://paste.yunohost.org/hohilezaxa

**Comment by ThatOneCalculator** [comment]
> But a big warning: Testing branch 14rc has a bug that stops calckey from working and fills the log with "bad system call"

Hold on... that definitely ISN'T normal. This may need to be reopened to find out why that's happening.

**Comment by lapineige** [comment]
> But a big warning: Testing branch 14rc has a bug that stops calckey from working and fills the log with "bad system call"


`bad system call` in the logs are here even in the normal version, I always saw them. Not sure it's an issue, I wasn't able to even diagnose where they are coming from.

But the thing that stop calckey is something else (I guess). But anyway the testing branch will wait for the next release candidate imho (as said above).

**Comment by lapineige** [comment]
> [db sonic]        Connecting to Sonic

Why is it connecting to Sonic ? Did you configure it ? I don't think we do it, and it's probably not installed.

**Comment by Ciechom** [comment]
The issue is that it absolutely stopped working. I mean I see errors in yunohost log viewer about internal server error 500 while connecting to relays, about an instance that has expired certificate and the website never loads. And there's not much more in logs apart from those errors that are happening every couple of seconds, I'm not sure but I don't recall it happening as often before even on this rc.

I wonder what will happen if I restore the instance from a backup that's 4 days old, while having it connected to s3 storage?

I also managed to back up this app in yunohost admin view while it's dead, so maybe I can restore it from this backup first to check if it's something else I broke on accident maybe?

**Comment by Ciechom** [comment]
I should also add that for 4 days it was working all right, it broke while I was sleeping and found out today when I woke up.

**Comment by ThatOneCalculator** [comment]
This seems like a deployment-level/system-level issue... perhaps something with system communication.

**Comment by ThatOneCalculator** [comment]
> Why is it connecting to Sonic ? Did you configure it ? I don't think we do it, and it's probably not installed.

It's a bug that logs "Connecting to Sonic" even if it's not. Fixed by https://codeberg.org/calckey/calckey/commit/1dbe44b2112593449c15f7034e866343dbd0a09c

**Comment by ThatOneCalculator** [comment]
Context: https://codeberg.org/calckey/calckey/issues/10306#issuecomment-940907

**Comment by Ciechom** [comment]
I'm terribly sorry for this whole mess I caused, it was DNS...

Of course, I panicked and deleted my instance (but was sane enough that I did a backup before), and now I have a new problem...

When I try to restore from backup (I tried the 14rc backup and the backup it did before updating to 14) I get an error... 

`2023-06-16 02:57:15,047: DEBUG - error: could not create bin directory: '/var/www/calckey/.cargo/bin': Permission denied (os error 13)
`

Here are the logs: https://paste.yunohost.org/raw/amesudozig

I'm terribly sorry for the whole trouble. I hope you can forgive me and help me out last time.


BTW, installing calckey from scratch worked, but I would like to not lose my posts.

**Comment by Ciechom** [comment]
I thought I might have broken my yunohost server, so I deployed another one.

On the new server, I still can't restore from backup, and I'm getting the same error.

Here are the latest logs: https://paste.yunohost.org/raw/nadixahiyu

Again, I'm terribly sorry for all the trouble I caused.

**Comment by Ciechom** [comment]
The previous backups were on test branch version.

Here's log on the backup that was done before upgrading: https://paste.yunohost.org/raw/vaqipocaki

**Comment by lapineige** [comment]
> The issue is that it absolutely stopped working. 

It's testing branch on a (now) known broken version. Do not use it in production (and have proper backup) please…
This may break your system once and for all.
I cannot guaranty you we can fix it in this cases (well in fact I can't in any case, but I least in the stable version it should be safer).


> 2023-06-16 02:57:15,047: DEBUG - error: could not create bin directory: '/var/www/calckey/.cargo/bin': Permission denied (os error 13) 

Wait what ?
Does Calckey also install Cargo (for rust) ? And the whole 500MB cache that might be a double of the system wide cargo ? 😅


> BTW, installing calckey from scratch worked, but I would like to not lose my posts.

One option could be to backup that new installation, and then merge all your previous backup file into this one. (be sure to use the same domain for the new install)
I don't know for sure, but it may work better.


Do you have an older than testing branch backup ?

**Comment by Ciechom** [comment]
> > The issue is that it absolutely stopped working.
> 
> It's testing branch on a (now) known broken version. Do not use it in production (and have proper backup) please… This may break your system once and for all. I cannot guaranty you we can fix it in this cases (well in fact I can't in any case, but I least in the stable version it should be safer).
> 
> > 2023-06-16 02:57:15,047: DEBUG - error: could not create bin directory: '/var/www/calckey/.cargo/bin': Permission denied (os error 13)
> 
> Wait what ? Does Calckey also install Cargo (for rust) ? And the whole 500MB cache that might be a double of the system wide cargo ? 😅
> 
> > BTW, installing calckey from scratch worked, but I would like to not lose my posts.

> One option could be to backup that new installation, and then merge all your previous backup file into this one. (be sure to use the same domain for the new install) I don't know for sure, but it may work better.

And how could I do it?

> Do you have an older than testing branch backup ?

Here is a post with stable import log: 
https://github.com/YunoHost-Apps/calckey_ynh/issues/38#issuecomment-1594166967

**Comment by Ciechom** [comment]
After trying to fuse working backup with data from the important backup I get this error:
![IMG_0558](https://github.com/YunoHost-Apps/calckey_ynh/assets/6024778/a36f72e0-6a2a-4bca-ae12-7b5c87acc6db)

**Comment by lapineige** [comment]
#43
