### ISSUE TITLE
14.0 RC3 - Still not able to import following.csv

### ISSUE THREAD

**Issue by Zeitverschreib** [YunoHost-Apps/calckey_ynh#45]
I was able to upgrade my setup to the latest RC, but still the same problem as before:

Uploading a following.csv works, the server tells me that it's starting to process the import, nothing happens.

I experienced the same on moppels.bar, which AFAIK is also hosted on Yunohost.

On calckey.world, the very same .csv worked just fine.

Where should I look (logfiles) for an explanation?

Thanks in advance.

**Comment by Zeitverschreib** [comment]
I think I found a/the solution to this particular problem.

allowedPrivateNetworks in default.yml is not set. This seems to keep the import routine from accessing the files on the Drive.

After I removed the #, the import of a followers.csv worked as expected.

**Comment by lapineige** [comment]
So what is the actual value right now ?
Thanks for sharing this !

**Comment by Zeitverschreib** [comment]
I simply uncommented the section and went with the standard value of 127.0.0.1.

Beginners luck, I guess.
