### ISSUE TITLE
Can't restore from backup after server change

### ISSUE THREAD

**Issue by belatedly** [YunoHost-Apps/calckey_ynh#49]
### Describe the bug

The restoration of my Calckey backup failed.

### Context

- Hardware: VPS on Debian 11
- YunoHost version: 11.2.3 (stable)
- I have access to my server: Webadmin and SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Yes, fresh Yunohost installation and restored the backup I made of the Calckey install
- Using, or trying to install package version/branch: See above
- If upgrading, current package version: n/a

### Steps to reproduce

- Backup existing Calckey install
- Install Yunohost on a new server
- Add the Calckey domain name and run LetsEncrypt
- Restore the backed up install

### Expected behavior

It should've restored

### Logs

https://paste.yunohost.org/raw/ikosupaqev

**Comment by lapineige** [comment]
> 2023-08-25 16:40:37,095: DEBUG - + sudo -u calckey env PATH=/opt/node_n/n/versions/node/19/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin pnpm install
2023-08-25 16:40:37,533: DEBUG - Internal Error: EACCES: permission denied, mkdir '/var/www/calckey/.cache/node/corepack'
2023-08-25 16:40:37,534: DEBUG - Error: EACCES: permission denied, mkdir '/var/www/calckey/.cache/node/corepack'

Oh, I know this one… See #44.
Does this help ? https://github.com/YunoHost-Apps/calckey_ynh/issues/44#issuecomment-1640983375

Can you share which version of Calckey was used for the backup ?

**Comment by belatedly** [comment]
> Can you share which version of Calckey was used for the backup ?

The last stable, 13.1.4.1 I believe it was. I will put that code into the restore file and try again - thanks for the quick reply!

**Comment by belatedly** [comment]
> Could not load info for archive '/home/yunohost.backup/archives/stonerparty.tar'... The info.json file cannot be retrieved (or is not a valid json).

Got that error, I am going to try again

**Comment by belatedly** [comment]
It happened again, I think the problem is that the created at/size info in the info.json is for the original archive. Not sure how to convert the date/time into that format

**Comment by belatedly** [comment]
Okay I ended up finding a converter to match the created time on the .tar from my laptop. I am still getting the error:
<img width="700" alt="Screenshot 2023-08-25 at 1 41 33 PM" src="https://github.com/YunoHost-Apps/calckey_ynh/assets/63966511/6e605997-4d01-4d98-b6e8-a850d5b9f986">

- I extracted the .tar that yunohost generated for it 
- replaced the content of the restore script with the updated one from that commit
- then created the tar with `tar -czf` on my Mac after editing the info.json file with the new created at/size info
- I also manually added a stonerpartynew.info.json to the folder because I'd seen one for an app I successfully restored, and set root as the owner to match the permissions on that one

**Comment by lapineige** [comment]
> I extracted the .tar that yunohost generated for it

That's the issue I think: it changes the permissions (and maybe owner, as it's not done as root on the server).
I don't remember it by heart, but there is a tar command (option) to replace on the server side one file inside of the archive with another, without extracting it. That's how I do it usually, it avoid the permissions issue.

Also don't replace the json, it should be good by default. A new one is likely to have wrong permissions, and to throw such an error.

**Comment by belatedly** [comment]
That worked! Thank you so much for your help. I searched and was able to find the commands, here is what I used in case anyone needs it in the future:

`sudo su - root`
`cd /home/yunohost.backup/archives/`
`tar -x -f backupfile.tar apps/calckey/settings/scripts/restore`
`nano apps/calckey/settings/scripts/restore` and pasted in that [new code section](https://github.com/YunoHost-Apps/calckey_ynh/commit/7d3d1cc22e1d72de245532317d6765c406ecd2a1#diff-f5c0550fe52eee02383ff6cfae9bb318bf2b757761b188f5f3137554b62d2c3a)
`tar --delete -f backupfile.tar apps/calckey/settings/scripts/restore`
`tar -uf backupfile.tar apps/calckey/settings/scripts/restore`
`reboot`

**Comment by lapineige** [comment]
Great, so we know have the confirmation that this PR solves the issue, and that the workaround I found is working in more than my special case.
Great !

Thanks for documenting this :)
