### ISSUE TITLE
Why is it marked as "low quality"?

### ISSUE THREAD

**Issue by ThatOneCalculator** [YunoHost-Apps/calckey_ynh#5]
Calckey:

![image](https://user-images.githubusercontent.com/44733677/210700311-14964352-8f00-4819-ac3d-bd1921b5534b.png)

Misskey:

![image](https://user-images.githubusercontent.com/44733677/210700335-de0c4f0d-b935-4972-8f68-ed27169049b2.png)

If the Calckey package is based off the Misskey package, why does the Calckey package have this label but the Misskey one doesn't?

**Comment by oufmilo** [comment]
Because the code is not finished still waiting , we're working on it.

**Comment by lapineige** [comment]
And we need to rerun continuous integration once it is included in app catalog, hence the app level will be possibly increased.
But it won't right now, as even installation fails.

Also I labelled it by mistake as "working" while is more "in progress".

**Comment by ericgaspar** [comment]
The `working`label put a nice little pressure to make it work 😬

**Comment by lapineige** [comment]
:rofl:
Well it does not install anyway and is correctly removed, so it's not a big deal ^^

**Comment by oufmilo** [comment]
The app is working 👍

**Comment by lapineige** [comment]
Well done !

**Comment by lapineige** [comment]
Tested manually, install, account creation, federation works as expected ! 🎉
Well done :D
